# Generated by Django 6.0.3 on 2026-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('alimentos', 'Alimentos'), ('herramientas', 'Herramientas'), ('otros', 'Otros')], max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
